# Use the official Node.js image as a base image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy all application files
COPY . .

# Expose the port your app runs on
EXPOSE 5002

# Command to run your app
CMD ["node", "server.js"]

