name: CI/CD Deploy to Kubernetes

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push API Gateway image
      uses: docker/build-push-action@v5
      with:
        context: ./API_Gateway
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/apigateway:latest

    - name: Build and push AuthService image
      uses: docker/build-push-action@v5
      with:
        context: ./AuthService
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/authservices:latest

    - name: Build and push BlogService image
      uses: docker/build-push-action@v5
      with:
        context: ./BlogService
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/blogservices:latest

    - name: Build and push ProfileService image
      uses: docker/build-push-action@v5
      with:
        context: ./ProfileService
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/profileservices:latest

    - name: Build and push CommentService image
      uses: docker/build-push-action@v5
      with:
        context: ./CommentService
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/commentservices:latest
 
    - name: Set up Kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f Q2/deployment.yaml
        kubectl apply -f Q2/services.yaml
